### PR TITLE
Fix DatePicker class props not accepting array as input (#494)

### LINKED ISSUE #494: Minor bug: array not supported for custom class input
```<datepicker ... :input-class="['some-class', {'conditional-class': someCondition}]"></datepicker>```

Despite being valid, produces a prop error `[Vue warn]: Invalid prop: type check failed for prop "inputClass". Expected String, Object, got Array.`

PR coming in shortly.

### PR DESCRIPTION
**Pull request by assembledadam**
Fixes #494

### CODE REVIEW

File: src/components/Datepicker.vue [hunk 1]
```diff
@@ -121,9 +121,9 @@ export default {
     highlighted: Object,
     placeholder: String,
     inline: Boolean,
-    calendarClass: [String, Object],
-    inputClass: [String, Object],
-    wrapperClass: [String, Object],
+    calendarClass: [String, Object, Array],
```
Comment (charliekassel) [inline src/components/Datepicker.vue]: The Picker* components will need this prop validation also

File: src/components/Datepicker.vue [hunk 2]
```diff
@@ -121,9 +121,9 @@ export default {
...
+    inputClass: [String, Object, Array],
```
Comment (charliekassel) [inline src/components/Datepicker.vue]: The DateInput component will need this as well.
